
---
- name: example file
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
   - name: installing git
     yum:
      name: git
      state: latest
   - name: installing tomact9
     yum:
       name: tomcat9
       state: present
...
